# Generated by Django 4.1.7 on 2023-02-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='IBAN', max_length=255)),
                ('owner_name', models.CharField(default='Joe', max_length=255)),
                ('tag', models.CharField(default='custom meta', max_length=255)),
                ('created_at', models.IntegerField(default=1677593906)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardWebPayInobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnURL', models.CharField(max_length=225)),
                ('CardType', models.CharField(choices=[('CB_VISA_MASTERCARD', 'CB VISA MASTERCARD'), ('MAESTRO', 'Maestro'), ('DINERS', 'Diners'), ('AMEX', 'Amex'), ('MASTERPASS', 'Masterpass'), ('P24', 'P24'), ('IDEAL', 'Ideal'), ('PAYLIB', 'Paylib'), ('BCMC', 'Bcmc')], max_length=255)),
                ('SecureMode', models.CharField(choices=[('DEFAULT', 'Default'), ('FORCE', 'Force'), ('NO_CHOICE', 'No_Choice')], max_length=255)),
                ('Billing', models.CharField(choices=[('Billing.FirstName', 'Option One'), ('Billing.LastName', 'Option Two'), ('Billing.Addres', 'Option Three')], max_length=255)),
                ('Culture', models.CharField(max_length=3)),
                ('Shipping', models.CharField(choices=[('Billing.FirstName', 'Option One'), ('Billing.LastName', 'Option Two'), ('Billing.Addres', 'Option Three')], max_length=255)),
                ('TemplateURL', models.CharField(max_length=255)),
                ('StatementDescriptor', models.CharField(max_length=255)),
                ('RedirectURLstring', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('RegisteredNamestring', models.TextField()),
                ('ClientId', models.TextField()),
                ('PrimaryThemeColour', models.CharField(max_length=7)),
                ('PrimaryButtonColour', models.CharField(max_length=7)),
                ('Logos', models.TextField()),
                ('TechEmails', models.CharField(blank=True, help_text='A comma-separated list of email addresses to use when contacting you for admin/commercial issues/communications.', max_length=255, null=True, verbose_name='Admin/Commercial Contact Emails')),
                ('AdminEmails', models.CharField(blank=True, help_text='A comma-separated list of email addresses to use when contacting you for admin/commercial issues/communications.', max_length=255, null=True, verbose_name='Admin/Commercial Contact Emails')),
                ('FraudEmails', models.CharField(blank=True, help_text='A comma-separated list of email addresses to use when contacting you for admin/commercial issues/communications.', max_length=255, null=True, verbose_name='Admin/Commercial Contact Emails')),
                ('Billing_Emails', models.CharField(blank=True, help_text='A comma-separated list of email addresses to use when contacting you for admin/commercial issues/communications.', max_length=255, null=True, verbose_name='Admin/Commercial Contact Emails')),
                ('PlatformCategorization', models.CharField(choices=[('PlatformCategorization.BusinessType', 'BusinessType'), ('PlatformCategorization.Sector', 'Sector')], max_length=255)),
                ('PlatformDescription', models.TextField()),
                ('PlatformURL', models.TextField()),
                ('HeadquartersAddress', models.CharField(choices=[('HeadquartersAddress.AddressLine1', 'Address One'), ('HeadquartersAddress.AddressLine2', 'Address Two'), ('HeadquartersAddress.City', 'City'), ('HeadquartersAddress.Region', 'Region'), ('HeadquartersAddress.PostalCode', 'Postal Code'), ('HeadquartersAddress.Country', 'Country')], max_length=255)),
                ('TaxNumber', models.TextField()),
                ('CompanyReference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DirectDebitWebPayInobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentTypePayIn', models.CharField(choices=[('CARD', 'Card'), ('DIRECT_DEBIT', 'Direct Debit'), ('PREAUTHORIZED', 'Preauthorized'), ('BANK_WIRE', 'Bank Wire'), ('APPLEPAY', 'Applepay'), ('GOOGLEPAY', 'Googlepay')], max_length=255)),
                ('ExecutionType', models.CharField(choices=[('WEB', 'Web'), ('DIRECT', 'Direct'), ('EXTERNAL_INSTRUCTION', 'External instruction')], max_length=255)),
                ('ReturnURL', models.CharField(default='URL', max_length=255)),
                ('DirectDebitType', models.CharField(choices=[('SOFORT', 'Sofort'), ('ELV', 'ELV'), ('GIROPAY', 'Giropay')], max_length=255)),
                ('SecureMode', models.CharField(choices=[('DEFAULT', 'Default'), ('FORCE', 'Force'), ('NO_CHOICE', 'No_Choice')], max_length=255)),
                ('Culture', models.CharField(choices=[('DE', 'de'), ('EN', 'en'), ('DA', 'da'), ('ES', 'es'), ('ET', 'et'), ('FI', 'fi'), ('FL', 'fl'), ('FR', 'pr'), ('EL', 'el'), ('HU', 'hu'), ('IT', 'it'), ('NL', 'nl'), ('NO', 'no'), ('PL', 'pl'), ('PT', 'pt'), ('SK', 'sk'), ('SV', 'SV'), ('sv', 'sv'), ('CS', 'cs')], max_length=255)),
                ('TemplateURL', models.CharField(max_length=255)),
                ('RedirectURL', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PayInobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentTypePayIn', models.CharField(choices=[('CARD', 'Card'), ('DIRECT_DEBIT', 'Direct Debit'), ('PREAUTHORIZED', 'Preauthorized'), ('BANK_WIRE', 'Bank Wire'), ('APPLEPAY', 'Applepay'), ('GOOGLEPAY', 'Googlepay')], max_length=255)),
                ('ExecutionType', models.CharField(choices=[('WEB', 'Web'), ('DIRECT', 'Direct'), ('EXTERNAL_INSTRUCTION', 'External instruction')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalWebPayInobject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=255)),
                ('CreationDate', models.CharField(blank=True, max_length=255)),
                ('AuthorId', models.CharField(max_length=255)),
                ('CreditedUserId', models.CharField(max_length=255)),
                ('DebitedFunds', models.CharField(choices=[('DebitedFunds.Currency', 'DebitedFunds.Currency'), ('DebitedFunds.Amount', 'DebitedFunds.Amount')], max_length=255)),
                ('CreditedFunds', models.CharField(choices=[('CreditedFunds.Currency', 'CreditedFunds.Currency'), ('CreditedFunds.Amount', 'CreditedFunds.Amount')], max_length=255)),
                ('Fees', models.CharField(choices=[('Fees.Currency', 'Fees.Currency'), ('Fees.Amount', 'Fees.Amount')], max_length=255)),
                ('Status', models.CharField(choices=[('CREATED', 'created'), ('SUCCEEDED', 'succeeded'), ('FAILED', 'failed')], max_length=255)),
                ('ResultMessage', models.CharField(max_length=255)),
                ('ExecutionDate', models.CharField(blank=True, max_length=255)),
                ('Type', models.CharField(choices=[('PAYIN', 'Pay In'), ('PAYOUT', 'Pay out'), ('TRANSFER', 'Transfer')], max_length=255)),
                ('Nature', models.CharField(choices=[('REGULAR', 'Regular'), ('REFUND', 'Refund'), ('REPUDIATION', 'Repudiation'), ('SETTLEMENT', 'Settlement')], max_length=255)),
                ('CreditedWalletId', models.CharField(max_length=255)),
                ('DebitedWalletId', models.CharField(max_length=255)),
                ('PaymentTypePayIn', models.CharField(choices=[('CARD', 'Card'), ('DIRECT_DEBIT', 'Direct Debit'), ('PREAUTHORIZED', 'Preauthorized'), ('BANK_WIRE', 'Bank Wire'), ('APPLEPAY', 'Applepay'), ('GOOGLEPAY', 'Googlepay')], max_length=255)),
                ('ExecutionType', models.CharField(choices=[('WEB', 'Web'), ('DIRECT', 'Direct'), ('EXTERNAL_INSTRUCTION', 'External instruction')], max_length=255)),
                ('RedirectURL', models.CharField(max_length=255)),
                ('Culture', models.CharField(choices=[('DE', 'de'), ('EN', 'en'), ('DA', 'da'), ('ES', 'es'), ('ET', 'et'), ('FI', 'fi'), ('FL', 'fl'), ('FR', 'pr'), ('EL', 'el'), ('HU', 'hu'), ('IT', 'it'), ('NL', 'nl'), ('NO', 'no'), ('PL', 'pl'), ('PT', 'pt'), ('SK', 'sk'), ('SV', 'SV'), ('sv', 'sv'), ('CS', 'cs')], max_length=255)),
                ('ShippingAddress', models.CharField(choices=[('ShippingAddress.RecipientName', 'ShippingAddress.RecipientName'), ('ShippingAddress.Address', 'ShippingAddress.Address'), ('ShippingAddress.Address.AddressLine1', 'ShippingAddress.Address.AddressLine1'), ('ShippingAddress.Address.AddressLine2', 'ShippingAddress.Address.AddressLine2'), ('ShippingAddress.Address.City', 'ShippingAddress.Address.City'), ('ShippingAddress.Address.Region', 'ShippingAddress.Address.Region'), ('ShippingAddress.Address.PostalCode', 'ShippingAddress.Address.PostalCode'), ('ShippingAddress.Address.Country', 'ShippingAddress.Address.Country')], max_length=255)),
                ('PaypalBuyerAccountEmail', models.CharField(max_length=255)),
                ('StatementDescriptor', models.CharField(max_length=255)),
            ],
        ),
    ]
