# Generated by Django 4.1.7 on 2023-02-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoApiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='IBAN', max_length=100)),
                ('owner_name', models.CharField(default='Joe', max_length=100)),
                ('tag', models.CharField(default='custom meta', max_length=100)),
                ('created_at', models.IntegerField(default=1677160690)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
